apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.15
        name: nginx
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
        - name: conf
          mountPath: /etc/nginx/conf.d
        - name: www
          mountPath: /www
      volumes:
      - name: nginx-conf
        hostPath:
          path: /kubernetes/nginx/nginx.conf
          type: File
      - name: conf
        hostPath:
          path: /kubernetes/nginx/conf.d
          type: Directory
      - name: www
        hostPath:
          path: /kubernetes/www
          type: Directory
      #标签选择器
      nodeSelector:
        type: nginx
      #设置污点可以调度到对应服务器
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "nginx"
        effect: "NoSchedule"
