apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  ports:
  - port: 80
    name: nginx-service80
    protocol: TCP
    targetPort: 80
    nodePort: 30002
  - port: 81
    name: nginx-service81
    protocol: TCP
    targetPort: 81
    nodePort: 30003
  selector:
    app: nginx
  type: NodePort
