apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  ports:
  - name: php
    port: 9000
    protocol: TCP
    targetPort: 9000
  #  nodePort: 9000
  selector:
    app: php-server
  #type: NodePort
