apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: nginx-pvc
  containers:
    - name: pv-pod-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
          protocol: TCP
          #targetPort: 80
          #nodePort: 80
      volumeMounts:
        - mountPath: "/www"
          name: pv-storage
